---
- name: Ensure www-data group is present
  group:
    name: www-data
    state: present

- name: Get passwd DB
  getent:
    database: passwd
  no_log: True
  register: esc_getent

- name: 'Check if "{{ esc_user }}" exists'
  set_fact:
    esc_user_found: '{{ esc_user in esc_getent["ansible_facts"]["getent_passwd"] }}'

  # When user doesn't exist
- block:

  - name: Throw random seeds
    set_fact:
      rnd_a: '{{ 4096 | random }}'
      rnd_b: '{{ 4096 | random }}'
      rnd_c: '{{ 4096 | random }}'
      rnd_d: '{{ 4096 | random }}'
      rnd_e: '{{ 4096 | random }}'
    no_log: true

  - name: Create random password and salt
    set_fact:
      password_raw: '{{ lookup("password", "/dev/null") }}'
      salt: '{{ rnd_a+rnd_b+rnd_c+rnd_d+rnd_e }}'
    no_log: true

  - name: 'Create "{{ esc_user }}" user with random password'
    user:
      name: '{{ esc_user }}'
      append: True
      create_home: False
      groups: www-data
      home: '{{ esc_path }}'
      move_home: False
      # The salt is roughly half of what rfc2898 requires due to the limitation in sha512_crypt
      password: '{{ password_raw | password_hash("sha512", salt[:16]) }}'
      shell: /bin/sh
    no_log: true

  when: not esc_user_found
  # Block end
