---
- name: Provision EteSync nginx config
  template:
    src: esc_nginx.j2
    dest: /etc/nginx/sites-available/esc_nginx.conf
  register: esc_nginx_provision

- name: Enable config
  file:
    src: /etc/nginx/sites-available/esc_nginx.conf
    dest: /etc/nginx/sites-enabled/esc_nginx.conf
    state: link
  register: esc_nginx_enable

- name: Ensure nginx is enabled and running
  systemd:
    name: nginx.service
    state: restarted
    masked: False
    enabled: True
  when: esc_nginx_provision.changed or esc_nginx_enable.changed
