---
- name: Ensure `strfile` is installed
  apt:
    name: fortune-mod
    state: present

- name: Create system-wide fortunes folder
  file:
    path: /usr/share/games/fortunes
    state: directory

- name: Propagate fortunes
  ansible.builtin.unarchive:
    creates: /usr/share/games/fortunes/st.txt
    decrypt: False
    dest: /usr/share/games/fortunes
    remote_src: False
    src: st.zip

- name: Check if DB is already present
  stat:
    path: /usr/share/games/fortunes/st.txt.dat
  register: fortunes_db

- name: Create fortunes search DB
  shell:
    cmd: 'strfile st.txt'
    chdir: '/usr/share/games/fortunes'
  when: not fortunes_db.stat.exists
