---
- name: Don't use vi mode in remote bash
  lineinfile:
    path: ~/.bashrc
    line: 'set -o emacs'
    regexp: 'set\ -o\ vi'
  when: dots_bash_emacs_mode

- name: Assembling remote-specific tmux config...
  block:

  - name: Lookup tmux.conf into a var
    set_fact:
      tmux_conf_orig: '{{ lookup("file", "tmux.conf").split("\n") | list }}'

  - name: Remove config options unsuitable for a remote tmux
    set_fact:
      tmux_conf_changed: '{{ tmux_conf_orig | difference(tmux_remove_lines) }}'

  - name: Strip comments
    set_fact:
      tmux_conf_changed: '{{ tmux_conf_changed | reject("match", "#") | reject("match", "\n") | list }}'
      tmux_conf_cleaned: []
      empty: ['']

    # Contrary to the filter() solution, this removes only elements that are empty strings
    # Additionaly, it does not pollute an output as loop() solution would
  - name: Remove empty lines
    set_fact:
      tmux_conf_cleaned: '{{ tmux_conf_changed | difference(empty) }}'

  - name: Copy tmux-remote.conf to ~/.local/etc/dotfiles and link from there
    block:

    - name: Create dotfiles folder
      file:
        path: '{{ ansible_env.HOME }}/.local/etc/dotfiles'
        state: directory

    - name: Write tmux config to a file
      copy:
        dest: '{{ ansible_env.HOME }}/.local/etc/dotfiles/tmux-remote.conf'
        content: '{{ tmux_conf_cleaned | join( "\n" ) }}'

    - name: Link remote-specific tmux config
      file:
        src: '{{ ansible_env.HOME }}/.local/etc/dotfiles/tmux-remote.conf'
        dest: '{{ ansible_env.HOME }}/.tmux.conf'
        state: link
        force: True

    when: dots_extract_dotfiles
    # block end

  - name: Link remote-specific tmux.conf from this role
    block:

    - name: Write tmux config to a file within this role
      copy:
        dest: '{{ role_path }}/files/tmux-remote.conf'
        content: '{{ tmux_conf_cleaned | join( "\n" ) }}'

    - name: Link remote-specific tmux config
      file:
        src: '{{ role_path }}/files/tmux-remote.conf'
        dest: '{{ ansible_env.HOME }}/.tmux.conf'
        state: link
        force: True

    when: not dots_extract_dotfiles
    # block end

  when: dots_change_tmux_prefix
  # block end
