---
- name: Assert that provisioning logic is sane
  assert:
    that:
      - dots_extract_dotfiles == true
    fail_msg: |
      Symlinking files from the local filesystem to a remote host is impossible.
  when: ansible_connection != "local"

- debug:
    msg: 'Will symlink dotfiles from this role to {{ ansible_env.HOME }}'
  when:
    - ansible_connection == "local"
    - not dots_extract_dotfiles

- debug:
    msg: 'Will copy dotfiles under {{ ansible_env.HOME }}/.local/etc/dotfiles on {{ ansible_host }} and link from there'
  when: dots_extract_dotfiles

- name: Hush login, setup terminfo and ~/.ssh
  import_tasks: dotfiles_init.yml
  tags:
    - dotfiles_init

- name: Backup existing dotfiles
  import_tasks: dotfiles_backup.yml
  tags:
    - dotfiles_backup

- name: Link dotfiles to $HOME
  import_tasks: dotfiles_link.yml
  tags:
    - dotfiles_link

- name: Adapt dotfiles for a remote host
  import_tasks: dotfiles_remote.yml
  tags:
    - dotfiles_remote

- name: Setup NeoVim
  import_tasks: dotfiles_neovim.yml
  when: dots_setup_neovim
  tags:
    - dotfiles_neovim

- name: Setup fortunes
  import_tasks: dotfiles_fortunes.yml
  become: True
  when: dots_setup_fortunes
  tags:
    - dotfiles_fortunes

- name: Run all relevant handlers
  meta: flush_handlers

- name: Finale
  debug:
    msg: |
      * DOTFILES ROLE IS COMPLETED *
