---
resolver: 'dnsmasq'
st_hosts: '/tmp/st-hosts'
st_hosts_in: '{{ st_hosts }}/incoming'
st_hosts_blacklist: '{{ playbook_dir }}/roles/hosts/files/blacklist'
st_hosts_whitelist: '{{ playbook_dir }}/roles/hosts/files/whitelist'
