#
# Restores permissions to system defaults.
# List is generated programmatically.
# Use at your own risk and as the last resort.
#

chmod 0444 /proc/buddyinfo
chown root:root /proc/buddyinfo
chmod 0444 /proc/cgroups
chown root:root /proc/cgroups
chmod 0444 /proc/consoles
chown root:root /proc/consoles
chmod 0444 /proc/crypto
chown root:root /proc/crypto
chmod 0444 /proc/devices
chown root:root /proc/devices
chmod 0444 /proc/diskstats
chown root:root /proc/diskstats
chmod 0444 /proc/dma
chown root:root /proc/dma
chmod 0444 /proc/execdomains
chown root:root /proc/execdomains
chmod 0444 /proc/fb
chown root:root /proc/fb
chmod 0444 /proc/filesystems
chown root:root /proc/filesystems
chmod 0444 /proc/interrupts
chown root:root /proc/interrupts
chmod 0444 /proc/iomem
chown root:root /proc/iomem
chmod 0444 /proc/ioports
chown root:root /proc/ioports
chmod 0444 /proc/kallsyms
chown root:root /proc/kallsyms
chmod 0444 /proc/key-users
chown root:root /proc/key-users
chmod 0444 /proc/keys
chown root:root /proc/keys
chmod 0444 /proc/locks
chown root:root /proc/locks
chmod 0444 /proc/misc
chown root:root /proc/misc
chmod 0400 /proc/pagetypeinfo
chown root:root /proc/pagetypeinfo
chmod 0444 /proc/partitions
chown root:root /proc/partitions
chmod 0444 /proc/sched_debug
chown root:root /proc/sched_debug
chmod 0444 /proc/schedstat
chown root:root /proc/schedstat
chmod 0400 /proc/slabinfo
chown root:root /proc/slabinfo
chmod 0444 /proc/softirqs
chown root:root /proc/softirqs
chmod 0444 /proc/swaps
chown root:root /proc/swaps
chmod 0444 /proc/zoneinfo
chown root:root /proc/zoneinfo
chmod 0600 /etc/adjtime
chown root:root /etc/adjtime
chmod 0600 /etc/bindresvport.blacklist
chown root:root /etc/bindresvport.blacklist
chmod 0600 /etc/crypttab
chown root:root /etc/crypttab
chmod 0600 /etc/deluser.conf
chown root:root /etc/deluser.conf
chmod 0600 /etc/e2scrub.conf
chown root:root /etc/e2scrub.conf
chmod 0600 /etc/fuse.conf
chown root:root /etc/fuse.conf
chmod 0600 /etc/hosts.allow
chown root:root /etc/hosts.allow
chmod 0600 /etc/hosts.deny
chown root:root /etc/hosts.deny
chmod 0600 /etc/kernel-img.conf
chown root:root /etc/kernel-img.conf
chmod 0600 /etc/libaudit.conf
chown root:root /etc/libaudit.conf
chmod 0600 /etc/locale.gen
chown root:root /etc/locale.gen
chmod 0600 /etc/login.defs
chown root:root /etc/login.defs
chmod 0600 /etc/mke2fs.conf
chown root:root /etc/mke2fs.conf
chmod 0600 /etc/modules
chown root:root /etc/modules
chmod 0600 /etc/pam.conf
chown root:root /etc/pam.conf
chmod 0600 /etc/sensors3.conf
chown root:root /etc/sensors3.conf
chmod 0440 /etc/sudoers
chown root:root /etc/sudoers
chmod 0644 /etc/sysctl.conf
chown root:root /etc/sysctl.conf
chmod 0644 /etc/ucf.conf
chown root:root /etc/ucf.conf
chmod 0644 /etc/xattr.conf
chown root:root /etc/xattr.conf
chmod 0644 /proc/mtrr
chown root:root /proc/mtrr
chmod 0755 /boot
chown root:root /boot
chmod 0755 /etc/apparmor.d
chown root:root /etc/apparmor.d
chmod 0755 /etc/binfmt.d
chown root:root /etc/binfmt.d
chmod 0755 /etc/cron.d
chown root:root /etc/cron.d
chmod 0755 /etc/cron.daily
chown root:root /etc/cron.daily
chmod 0755 /etc/cron.monthly
chown root:root /etc/cron.monthly
chmod 0755 /etc/cron.weekly
chown root:root /etc/cron.weekly
chmod 0755 /etc/default
chown root:root /etc/default
chmod 0755 /etc/dhcp
chown root:root /etc/dhcp
chmod 0755 /etc/initramfs-tools
chown root:root /etc/initramfs-tools
chmod 0755 /etc/iproute2
chown root:root /etc/iproute2
chmod 0755 /etc/kernel
chown root:root /etc/kernel
chmod 0755 /etc/ldap
chown root:root /etc/ldap
chmod 0755 /etc/libblockdev
chown root:root /etc/libblockdev
chmod 0755 /etc/lightdm
chown root:root /etc/lightdm
chmod 0755 /etc/logcheck
chown root:root /etc/logcheck
chmod 0755 /etc/logrotate.d
chown root:root /etc/logrotate.d
chmod 0755 /etc/modprobe.d
chown root:root /etc/modprobe.d
chmod 0755 /etc/modules-load.d
chown root:root /etc/modules-load.d
chmod 0755 /etc/pam.d
chown root:root /etc/pam.d
chmod 0755 /etc/polkit-1
chown root:root /etc/polkit-1
chmod 0755 /etc/rsyslog.d
chown root:root /etc/rsyslog.d
chmod 0755 /etc/security
chown root:root /etc/security
chmod 0755 /etc/selinux
chown root:root /etc/selinux
chmod 0755 /etc/sensors.d
chown root:root /etc/sensors.d
chmod 0755 /etc/skel
chown root:root /etc/skel
chmod 0755 /etc/sudoers.d
chown root:root /etc/sudoers.d
chmod 0755 /etc/sysctl.d
chown root:root /etc/sysctl.d
chmod 0755 /etc/tmpfiles.d
chown root:root /etc/tmpfiles.d
chmod 0755 /etc/udev
chown root:root /etc/udev
chmod 0755 /etc/update-motd.d
chown root:root /etc/update-motd.d
chmod 0555 /proc/acpi
chown root:root /proc/acpi
chmod 0555 /proc/bus
chown root:root /proc/bus
chmod 0555 /proc/fs
chown root:root /proc/fs
chmod 0555 /proc/irq
chown root:root /proc/irq
chmod 0555 /proc/pressure
chown root:root /proc/pressure
chmod 0555 /proc/sysvipc
chown root:root /proc/sysvipc
chmod 0555 /proc/tty
chown root:root /proc/tty
chmod 0755 /sys/block
chown root:root /sys/block
chmod 0755 /sys/bus/memory
chown root:root /sys/bus/memory
chmod 0755 /sys/bus/nvmem
chown root:root /sys/bus/nvmem
chmod 0755 /sys/bus/scsi
chown root:root /sys/bus/scsi
chmod 0755 /sys/class/block
chown root:root /sys/class/block
chmod 0755 /sys/class/firmware
chown root:root /sys/class/firmware
chmod 0755 /sys/class/iommu
chown root:root /sys/class/iommu
chmod 0755 /sys/class/mem
chown root:root /sys/class/mem
chmod 0755 /sys/class/scsi_device
chown root:root /sys/class/scsi_device
chmod 0755 /sys/class/scsi_disk
chown root:root /sys/class/scsi_disk
chmod 0755 /sys/class/scsi_host
chown root:root /sys/class/scsi_host
chmod 0755 /sys/dev/block
chown root:root /sys/dev/block
chmod 0755 /sys/firmware
chown root:root /sys/firmware
chmod 1700 /sys/fs/bpf
chown root:root /sys/fs/bpf
chmod 0755 /sys/fs/ext4
chown root:root /sys/fs/ext4
chmod 0750 /sys/fs/pstore
chown root:root /sys/fs/pstore
chmod 0755 /sys/hypervisor
chown root:root /sys/hypervisor
chmod 0755 /sys/module
chown root:root /sys/module
chmod 0755 /sys/power
chown root:root /sys/power
chmod 0755 /var/backups
chown root:root /var/backups
chmod 0755 /var/cache/apparmor
chown root:root /var/cache/apparmor
chmod 0755 /var/cache/debconf
chown root:root /var/cache/debconf
chmod 0755 /var/lib/misc
chown root:root /var/lib/misc
chmod 0755 /var/lib/pam
chown root:root /var/lib/pam
chmod 0755 /var/lib/sudo
chown root:root /var/lib/sudo
chmod 0755 /var/lib/ucf
chown root:root /var/lib/ucf
chmod 2775 /var/local
chown root:staff /var/local
chmod 0755 /var/log/apt
chown root:root /var/log/apt
