---
- name: Run preflight checks
  import_tasks: preflight.yml
  become: True
  tags:
    - base_preflight

- name: Setup hostname, locale and timezone
  import_tasks: identity.yml
  become: True
  tags:
    - base_locale

- name: Set dpkg overrides
  import_tasks: dpkg_overrides.yml
  when: base_set_dpkg_overrides
  tags:
    - base_dpkg_overrides

- name: Bootstrap packages
  import_tasks: pkg_bootstrap.yml
  become: True
  tags:
    - base_pkg_bootstrap

- name: Install and configure Knot-resolver
  import_tasks: pkg_resolver.yml
  become: True
  when: base_kresd_install
  tags:
    - base_knot

- name: Install and configure thermald
  import_tasks: thermald.yml
  become: True
  when:
    - base_thermald_profiles | length > 0
    - '"Intel" in cpu_vendor'
  tags:
    - base_thermald

- name: Configure kernel modules
  import_tasks: modules.yml
  become: True
  tags:
    - base_settings

- name: Set various settings
  import_tasks: settings.yml
  become: True
  tags:
    - base_settings

- name: Configure GRUB
  import_tasks: grub.yml
  become: True
  tags:
    - base_grub

- name: Initialise GPG
  import_tasks: gpg.yml
  become: False
  tags:
    - base_gpg

- name: Configure OpenSSH
  import_tasks: openssh.yml
  become: True
  tags:
    - base_openssh

- name: Configure UFW
  import_tasks: ufw.yml
  become: True
  tags:
    - base_ufw

- name: Reconfigure console via dpkg
  import_tasks: dpkg_console.yml
  become: True
  when: base_set_dpkg_console
  tags:
    - base_dpkg_console

  # R.I.P sshguard
  # https://tracker.debian.org/news/1241807/sshguard-removed-from-testing/

- name: Install various firmware
  import_tasks: firmware.yml
  become: True
  tags:
    - base_firmware

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Run all relevant handlers
  meta: flush_handlers

- name: Reboot if system can't pick-up updated kernel and/or userland
  debug:
    msg: 'Rebooting {{ ansible_hostname | upper }} @ {{ ansible_host }}'
  notify:
    - reboot host
  when: reboot_required.results | json_query( '[*].stat.exists' ) | string == "[True]"

- name: Finale
  debug:
    msg: |
      * BASE ROLE IS COMPLETED *
      Please login and `passwd` all relevant users.
