---
- name: Download latest hosts from the mirrors
  import_tasks: fetch_hosts.yml
  delegate_to: localhost
  run_once: True
  tags:
    - hosts_download

- name: Assemble hosts in the single file and clean-up afterwards
  import_tasks: assemble_hosts.yml
  delegate_to: localhost
  run_once: True
  tags:
    - hosts_assemble

- name: Copy new `hosts_blocked` to the /etc
  import_tasks: copy_hosts.yml
  tags:
    - hosts_copy

- name: Finale
  debug:
    msg: |
      * HOSTS ROLE IS COMPLETED *
