---
- name: Playbook summary
  debug:
    msg: |
      Server`s public key: {{ wg_sum_pubkey }}
      Provisioned clients: {{ wg_clients | length }}
      Provisioned endpoints: {{ wg_endpoints | length }}

- name: Finale
  debug:
    msg: |
      * WIREGUARD ROLE IS COMPLETED *
